---
- name: apply NeuVector manifests
  hosts: borg1
  tasks:
  - name: copy out calicoctl manifest to /root of the control node
    copy:
      src: files/neu.sh
      dest: /root/neu.sh
    tags: 
      - sec
      - neuvector
      - neuscriptdeploy
  - name: execute NeuVector sequence
    shell: bash /root/neu.sh
    tags: 
      - sec
      - neuvector
      - neumanifest
 ...
