---
- name: apply NeuVector manifests
  hosts: borg1
  tasks:
  - name: copy out NeuVector manifest script to borg1
    copy:
      src: files/neu.sh
      dest: /root/neu.sh
    tags: 
      - sec
      - neuvector
      - neuscriptdeploy
  - name: ccopy out psp, note deprecation
    copy:
      src: files/nv_psp.yaml
      dest: /root/nv_psp.yaml
    tags: 
      - sec
      - neuvector
      - neuscriptdeploy
  - name: execute NeuVector sequence
    shell: bash /root/neu.sh
    tags: 
      - sec
      - neuvector
      - neumanifest
 ...
